[project]
name = "brasa"
version = "0.1.0"
description = "MicroPython developer tools — flash, deploy, watch, monitor."
readme = "README.md"
authors = [
    { name = "Martin Miglio", email = "marmig0404@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "typer",
    "pyserial",
    "watchfiles",
    "mpremote>=1.24.0",
    "httpx",
]

[project.scripts]
brasa = "brasa.cli:main"

[build-system]
requires = ["uv_build>=0.10.12,<0.11.0"]
build-backend = "uv_build"
